FROM node:latest

WORKDIR /home/lit

COPY . .

#RUN npm install -g create-react-app
#RUN npm install -g yarn
RUN yarn global add create-react-app
RUN yarn
#RUN yarn install
RUN yarn run build

RUN yarn global add serve

EXPOSE 3000
